
####
##    default_config.yml
###
#

---
### нафиг не нужные опции ( но используемые )
# url отправной точки
fedresurs_url: 'http://bankrot.fedresurs.ru/TradeList.aspx'
# вид торгов - "Публичое предложение" (значение поля "3")
vid_torgov: '3'
#
### федресурс жалуется бывает на частые запросы, поэтому задержки установлены
# задержка перед посылом запроса для форм, с
form_timeout: 3
# задержка перед переходом по ссылкам, с
links_follow_timeout: 3
# не используется
# максимально количество провальных запросов подряд, штук
#request_failure_count: 5
#
# файл базы данных
db_file: './db/lots.sqlite3'
#
# координаты домашней точки
home_geolocation: [ 55.834218, 37.623497 ]
# парсятся только москва, мо и соседние области, для расширения нужно править
# в сырцах метод loop_by_regions, файл process_fedresurs.rb
# максимальное удаление объекта, км
max_distance: 300
#
# для дебага
# лог-файл
logfile: './log/log.txt'
# направление(ия) выхлопа логов #=> :both | :file | :stdout
log_output: :both
# лог dbg-сообщений?
log_dbg: true
#
# если репорт не пуст, то отправляется на это мыло
# для отправки нужно раскоментировать строку
# с системной командой `mail` после настройки (а может установи и настройки)
# штатного sendmail
report_email: kashmatov@mail.ru
# В этот файл можно добавить любую опцию и использовать в коде потом
# как CFG.my_new_option
# по типу: ключ(имя метода) - значение
# ключ должен быть ruby-вылидным именем метода
